# Configuration for jekyll
# NOTICE: GitHub forces to set `safe: true` in order to prohibit using plugins.
safe: true
source: .
destination: ./_site
plugins_dir: ./_plugins
lsi: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'vender']
gems: [jekyll-paginate]

# Configuration for url/path
# NOTICE:
# * `baseurl`: Being set as absolute path is recommended.
# * No need '/' at the end of url/path.
# * Project page:
#   url: http://USERNAME.github.com/REPOSITORY
#   baseurl: /REPOSITORY
url: http://klein.uk
baseurl: 

# Configuration for permalink
# `permalink`: none, pretty or /blog/:categories/:title.html
permalink: /blog/:year/:month/:title/

# Configuration for site
title: thilo klein
description: Economist, Analyst, dabbler on the side
name: klein.uk
author: Thilo Klein
email: 

# Configuration for blog
lang: en
paginate: 9
columns: 4
date_format: "%B %d, %Y"
truncate_len: 250

# Configuration for asides/recent_posts.html
recent_posts: 5

# Configuration for navbar.html
navbar_list:
- name: Blog
  link: /index.html
- name: Research
  link: /research/index.html
- name: Software
  link: /research/software/index.html
- name: Teaching
  link: /teaching/index.html
  dropdown: &dropdown
  - name: Game Theory
    link: /teaching/index.html#games
  - name: Econometrics
    link: /teaching/index.html#econometrics
  - name: Finance
    link: /teaching/index.html#finance
  - name: Data Viz
    link: /teaching/index.html#r
- name: CV
  link: /research/cv_ThiloKLEIN.pdf

# Configuration for bootstrap and color theme
# `bootstrap`:
# custom, original, amelia, cerulean, cyborg, journal,
# readable, simplex, slate, spacelab, spruce, superhero, united
bootstrap: custom
bootstrap_ver: 2.3.2
bootswatch_ver: 2.3.2

# Configuration for responsive break point when using 'custom'.
responsive_bp: 768

# Configuration for asides.html
# CAUTION: `themes` should be false to put the script.html at the bottom.
asides:
    about: true
    search: false
    recent_posts: true
    tweets: false
    github: true
    archive_tabs: true
    themes: true

# Configuration for pygments
# `pygments_style`:
# autumn, borland, bw, colorful, default, emacs, friendly, fruity,
# github, manni, monokai, murphy, native, pastie, perldoc, tango, trac, vs
# pygments_style: github

# Configuration for jQuery
jquery_ver: 1.10.2

#-----------------------------------
# Configuration for 3rd party script
#-----------------------------------
disqus:
    short_name: admin
    comment_count: false
    developer_mode: true

#feedburner:
#    id: YOUR_SITE_ID

google_analytics:
    account: UA-50356874-3

google_plus_one:
    size: medium

# `xfbml` will break some styles on android 2.3 native browser (Optimus L-01D).
# `locale`: ja_JP, en_US, es_LA, fr_FR, de_DE, it_IT, zh_CN, ko_KR, ...
facebook:
    xfbml: false
    locale: en_US

twitter:
    username: kleindotuk
    count: 3
    exclude_replies: true
    show_screen_name: true
    show_follower_count: false
    widget_id: 635095724460478464

github:
    username: thiloklein
    count: 3

pocket: true

hatena: true

excerpt_separator: <!--more-->

